### ISSUE TITLE
Intend to carry out the updates of the release on the 16th?

### ISSUE THREAD

**Issue by conradosaud** [Daweyy/WavenData#1]
Hello, do you intend to make updates to this repository with the release of the game tomorrow, the 16th?
Do you have any discord to contact? If you prefer, my discord is: conrado2689 need to talk with you

**Comment by ghost** [comment]
Hello,
I updated the repo yesterday with all the game updates I missed (as the process isn't fully automated).
It's currently up to date with early access and I plan to keep it that way for as long as possible.
Sent you a message on Discord
