### ISSUE TITLE
WavenRE

### ISSUE THREAD

**Issue by krm35** [Daweyy/WavenData#3]
Hello,

Do you plan to give access to this https://github.com/Daweyy/WavenRE 

Thanks

**Comment by Faareoh** [comment]
https://github.com/Daweyy/WavenData/issues/2#issuecomment-2131435843

**Comment by Daweyy** [comment]
Hello,
I'm totally planning on open-sourcing it, it's just on hold it until Dofus Unity at this point.
The project itself is pretty basic but could lead to unwanted usages or even Ankama to search some workaround, not my point in both cases for sure.

Thanks for your interest,
Daweyy

**Comment by krm35** [comment]
Ok thanks see u
